version: '2'
services:
  influxdb:
    image: influxdb:1.3-alpine
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
      - "8000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    depends_on:
      - influxdb
